OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "I'm sorry for taking up so much of\n"
    .string "BILL's time.\p"
    .string "I'm also sorry for being such a \n"
    .string "poor host on your visit here.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "Okay, this is good…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "I did it!\n"
    .string "I linked up with LANETTE!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "{PLAYER}…\n"
    .string "{PLAYER}, I did it!\p"
    .string "I've managed to link up with\n"
    .string "TRAINERS in the HOENN region!\p"
    .string "Finally, the Network Machine is\n"
    .string "fully operational!\p"
    .string "{PLAYER}, I owe it all to you!\p"
    .string "Thanks to you, my dream came\n"
    .string "true…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "I…\n"
    .string "I'm not crying.\p"
    .string "That's enough about me!\p"
    .string "{PLAYER}, you're going to keep\n"
    .string "looking for exotic POKéMON, right?\p"
    .string "I wish you the best of luck!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "CELIO: Hello!\p"
    .string "{PLAYER}, I've been hearing rumors\n"
    .string "about you.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "{PLAYER}, what's your favorite kind\n"
    .string "of POKéMON?\p"
    .string "BILL is a POKéMANIAC, so he loves\n"
    .string "every kind.\p"
    .string "Apparently, the first one he caught\n"
    .string "was an ABRA.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "By the way, {PLAYER}, you're from\n"
    .string "PALLET TOWN, aren't you?\p"
    .string "I've heard that it's a quiet and\n"
    .string "pleasant place.\p"
    .string "BILL's hometown is GOLDENROD CITY,\n"
    .string "where his folks still live.\p"
    .string "I've heard that it's quite the\n"
    .string "festive, bustling city.\p"
    .string "I'd like to go there one day.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "{PLAYER}, is there anything that\n"
    .string "you can't stand?\p"
    .string "Apparently, BILL simply can't\n"
    .string "stomach milk at all.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "Oh, you're a stranger here!\n"
    .string "Hi! Where did you come from?\p"
    .string "…PALLET TOWN?\n"
    .string "I don't know it!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string "On this island, there's an enormous\n"
    .string "volcano.\p"
    .string "It hasn't erupted lately, so why\n"
    .string "not enjoy a hike?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "I wish I could trade POKéMON with\n"
    .string "my boyfriend who lives far away…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "I traded POKéMON with my boyfriend\n"
    .string "far away!\p"
    .string "Everyone's saying that we can\n"
    .string "thank you and CELIO.\p"
    .string "So, thank you!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string "Network Machine\n"
    .string "Link Level 0\p"
    .string "…POKéMON Storage System under\n"
    .string "adjustment…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "Network Machine\n"
    .string "Link Level 1\p"
    .string "Link established with the KANTO\n"
    .string "region.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "Network Machine\n"
    .string "Link Level 2\p"
    .string "Link established with the KANTO\n"
    .string "and HOENN regions.$"
