#ifndef GUARD_CONSTANTS_MENU_H
#define GUARD_CONSTANTS_MENU_H

#define SCR_MENU_CANCEL 127
#define SCR_MENU_UNSET  255

enum {
	MULTICHOICE_YES_NO = 0,
	MULTICHOICE_EEVEELUTIONS,
	MULTICHOICE_TRAINER_CARD_ICON_TINT,
	MULTICHOICE_HOF_QUIT,
	MULTICHOICE_EGGS_QUIT,
	MULTICHOICE_VICTORIES_QUIT,
	MULTICHOICE_HOF_EGGS_QUIT,
	MULTICHOICE_HOF_VICTORIES_QUIT,
	MULTICHOICE_EGGS_VICTORIES_QUIT,
	MULTICHOICE_HOF_EGGS_VICTORIES_QUIT,
	MULTICHOICE_EXIT,
	MULTICHOICE_EXIT_2,
	MULTICHOICE_EXIT_3,
	MULTICHOICE_BIKE_SHOP,
	MULTICHOICE_GAME_CORNER_POKEMON_PRIZES,
	MULTICHOICE_TRAINER_SCHOOL_WHITEBOARD,
	MULTICHOICE_YES_NO_INFO,
	MULTICHOICE_SINGLE_DOUBLE_MULTI_INFO_EXIT,
	MULTICHOICE_YES_NO_INFO_2,
	MULTICHOICE_CHALLENGE_INFO_EXIT,
	MULTICHOICE_ROOFTOP_B1F,
	MULTICHOICE_HELIX,
	MULTICHOICE_DOME,
	MULTICHOICE_AMBER,
	MULTICHOICE_HELIX_AMBER,
	MULTICHOICE_DOME_AMBER,
	MULTICHOICE_CELADON_VENDING_MACHINE,
	MULTICHOICE_GAME_CORNER_COIN_PURCHASE_COUNTER,
	MULTICHOICE_EXCELLENT_NOT_SO_BAD,
	MULTICHOICE_RIGHT_LEFT,
	MULTICHOICE_GAME_CORNER_TMPRIZES,
	MULTICHOICE_DEPT_STORE_ELEVATOR,
	MULTICHOICE_THIRSTY_GIRL_FRESH_WATER,
	MULTICHOICE_THIRSTY_GIRL_SODA_POP,
	MULTICHOICE_THIRSTY_GIRL_FRESH_WATER_SODA_POP,
	MULTICHOICE_THIRSTY_GIRL_LEMONADE,
	MULTICHOICE_THIRSTY_GIRL_FRESH_WATER_LEMONADE,
	MULTICHOICE_THIRSTY_GIRL_SODA_POP_LEMONADE,
	MULTICHOICE_THIRSTY_GIRL_FRESH_WATER_SODA_POP_LEMONADE,
	MULTICHOICE_TRADE_CENTER_COLOSSEUM,
	MULTICHOICE_LINK_WIRELESS,
	MULTICHOICE_GAME_CORNER_BATTLE_ITEM_PRIZES,
	MULTICHOICE_ROCKET_HIDEOUT_ELEVATOR,
	MULTICHOICE_LINKED_DIRECT_UNION,
	MULTICHOICE_ISLAND_23,
	MULTICHOICE_ISLAND_13,
	MULTICHOICE_ISLAND_12,
	MULTICHOICE_TRADE_COLOSSEUM_CRUSH,
	MULTICHOICE_POKEJUMP_DODRIO,
	MULTICHOICE_TRADE_COLOSSEUM_2,
	MULTICHOICE_MUSHROOMS,
	MULTICHOICE_TRADE_COLOSSEUM_BLANK_CRUSH,
	MULTICHOICE_TRADE_COLOSSEUM_BLANK,
	MULTICHOICE_SEVII_NAVEL,
	MULTICHOICE_SEVII_BIRTH,
	MULTICHOICE_SEVII_NAVEL_BIRTH,
	MULTICHOICE_SEAGALLOP_V23,
	MULTICHOICE_SEAGALLOP_V13,
	MULTICHOICE_SEAGALLOP_V12,
	MULTICHOICE_SEAGALLOP_VERMILION,
	MULTICHOICE_JOIN_OR_LEAD,
	MULTICHOICE_TRAINER_TOWER_MODE,
	MULTICHOICE_TUTOR_PUNCHES,
	MULTICHOICE_NONE,
};

#define LISTMENU_BADGES                    0
#define LISTMENU_SILPHCO_FLOORS            1
#define LISTMENU_ROCKET_HIDEOUT_FLOORS     2
#define LISTMENU_DEPT_STORE_FLOORS         3
#define LISTMENU_WIRELESS_LECTURE_HEADERS  4
#define LISTMENU_BERRY_POWDER              5
#define LISTMENU_TRAINER_TOWER_FLOORS      6

// Std String Ids
#define STDSTRING_COOL              0
#define STDSTRING_BEAUTY            1
#define STDSTRING_CUTE              2
#define STDSTRING_SMART             3
#define STDSTRING_TOUGH             4
#define STDSTRING_COOL2             5
#define STDSTRING_BEAUTY2           6
#define STDSTRING_CUTE2             7
#define STDSTRING_SMART2            8
#define STDSTRING_TOUGH2            9
#define STDSTRING_ITEMS             10
#define STDSTRING_KEY_ITEMS         11
#define STDSTRING_POKEBALLS         12
#define STDSTRING_TMHMS             13
#define STDSTRING_BERRIES           14
#define STDSTRING_BOULDER_BADGE     15
#define STDSTRING_CASCADE_BADGE     16
#define STDSTRING_THUNDER_BADGE     17
#define STDSTRING_RAINBOW_BADGE     18
#define STDSTRING_SOUL_BADGE        19
#define STDSTRING_MARSH_BADGE       20
#define STDSTRING_VOLCANO_BADGE     21
#define STDSTRING_EARTH_BADGE       22
#define STDSTRING_COINS             23
#define STDSTRING_ITEMS_POCKET      24
#define STDSTRING_KEY_ITEMS_POCKET  25
#define STDSTRING_POKEBALLS_POCKET  26
#define STDSTRING_TM_CASE           27
#define STDSTRING_BERRY_POUCH       28

#endif //GUARD_CONSTANTS_MENU_H
