VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "I'm the FISHING GURU!\n"
    .string "I simply looove fishing!\p"
    .string "Tell me, do you like to fish?$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "Grand! I like your style.\n"
    .string "Take this and fish, young friend!$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "Oh…\n"
    .string "That's so disappointing…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"

