CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "For long outings, you should buy\n"
    .string "REVIVE.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "2F: TRAINER'S MARKET\n"
    .string "Top-Grade Items for TRAINERS!$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "We have a customer, LANCE, who\n"
    .string "occasionally comes.\p"
    .string "He always buys capes.\p"
    .string "I wonder… Does he have many\n"
    .string "identical capes at home?$"
