gText_WouldYouLikeToSaveTheGame::
	.string "Would you like to save the game?$"

gText_SavingDontTurnOffThePower::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} saved the game.$"

gText_DifferentGameFile::
	.string "WARNING!\n"
	.string "A different save file is present.\p"
	.string "If you save now, the previous\n"
	.string "save file will be entirely lost.\p"
	.string "Overwrite the previous save?$"
