Route4_Text_TrippedOverGeodude::
    .string "Ouch! I tripped over a rocky\n"
    .string "POKéMON, GEODUDE!$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Oh, wow, that's the BOULDERBADGE!\n"
    .string "You got it from BROCK, didn't you?\p"
    .string "BROCK is cool. He's not just tough.\n"
    .string "People like and respect him.\p"
    .string "I want to become a GYM LEADER\n"
    .string "like him.$"

Route4_Text_CrissyIntro::
    .string "I came to MT. MOON in search of\n"
    .string "mushroom POKéMON.$"

Route4_Text_CrissyDefeat::
    .string "After all I did to catch them!$"

Route4_Text_CrissyPostBattle::
    .string "There might not be any more\n"
    .string "mushrooms here.\p"
    .string "I think I got them all.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "Tunnel Entrance$"

Route4_Text_RouteSign::
    .string "ROUTE 4\n"
    .string "MT. MOON - CERULEAN CITY$"

Route4_Text_PunchesTutor_WhichMove::
    .string "Which move?$"

Route4_Text_PunchesTutor_WhichMon::
    .string "Which POKéMON?$"

Route4_Text_PunchesTutor_Done::
    .string "It is done!$"

Route4_Text_PunchesTutor_Declined::
    .string "Fuck you!$"
