Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a man fishing!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's POKéMON TOWER!$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymore::
    .string "My POKéMON's ashes are stored in\n"
    .string "POKéMON TOWER.\p"
    .string "You can have this TM.\n"
    .string "I don't need it anymore…$"

Route12_NorthEntrance_2F_Text_ExplainTM::
    .string "TM09 is a move called PETAL DANCE…\n"
    .string "It was my GLOOM's favourite. Sniff…$"

Route12_NorthEntrance_2F_Text_NoRoomForTM::
    .string "You don't have room for this.$"
