CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Hello!\n"
    .string "Welcome to CELADON DEPT. STORE.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1F: SERVICE COUNTER\n"
    .string "2F: TRAINER'S MARKET\p"
    .string "3F: TV GAME SHOP\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "5F: TM CORNER\n"
    .string "ROOFTOP: VENDING MACHINES$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1F: SERVICE COUNTER$"

